package calebxzhou.rdi.common.model

enum class GameRuleValueType { BOOLEAN, INTEGER }

data class GameRule(
	val id: String,
	val name: String,
	val description: String,
	val category: String,
	val valueType: GameRuleValueType,
	var value: String,
	val effect: String? = null,
)

val AllGameRules: List<GameRule> = listOf(
	GameRule("allowEnteringNetherUsingPortals", "允许进入下界", "控制玩家能否进入下界。", "杂项", GameRuleValueType.BOOLEAN, "true", "实体是否能通过下界传送门进入下界。"),
	GameRule("allowFireTicksAwayFromPlayer", "允许火在远离玩家处蔓延", "控制火和熔岩能否在距离任何玩家超过8个区块处蔓延。", "世界更新", GameRuleValueType.BOOLEAN, "false", "远离玩家的火是否由熔岩生成、蔓延及自然熄灭。"),
	GameRule("announceAdvancements", "进度通知", "是否在聊天框公告玩家进度达成。", "聊天", GameRuleValueType.BOOLEAN, "true"),
	GameRule("blockExplosionDropDecay", "在方块交互爆炸中，一些方块不会掉落战利品", "在与方块交互引起的爆炸中，部分被破坏方块的掉落物会被炸毁。", "掉落", GameRuleValueType.BOOLEAN, "true", "床/重生锚爆炸的方块是否有概率不掉落。"),
	GameRule("commandBlockOutput", "广播命令方块输出", "命令方块输出是否向管理员显示。", "聊天", GameRuleValueType.BOOLEAN, "true"),
	GameRule("commandBlocksEnabled", "启用命令方块", "命令方块是否被启用。", "杂项", GameRuleValueType.BOOLEAN, "true"),
	GameRule("commandModificationBlockLimit", "命令修改方块数量限制", "单条命令(如fill/clone)最多能更改的方块数量。", "杂项", GameRuleValueType.INTEGER, "32768"),
	GameRule("disableElytraMovementCheck", "启用鞘翅移动检测", "是否停止检查鞘翅玩家移动速度。", "玩家", GameRuleValueType.BOOLEAN, "true", "可减轻延迟卡顿，但可能导致飞行过快。"),
	GameRule("disablePlayerMovementCheck", "启用玩家移动检测", "是否停止检查并限制玩家移动速度。", "玩家", GameRuleValueType.BOOLEAN, "true"),
	GameRule("disableRaids", "启用袭击", "是否禁用袭击。", "生物", GameRuleValueType.BOOLEAN, "true"),
	GameRule("doDaylightCycle", "游戏内时间流逝", "是否进行昼夜更替和月相变化。", "世界更新", GameRuleValueType.BOOLEAN, "true"),
	GameRule("doEntityDrops", "非生物实体掉落", "控制矿车、物品展示框、船等的物品掉落。", "掉落", GameRuleValueType.BOOLEAN, "true"),
	GameRule("doFireTick", "火焰蔓延", "火是否蔓延及自然熄灭。", "常用", GameRuleValueType.BOOLEAN, "true"),
	GameRule("doImmediateRespawn", "立即重生", "玩家死亡时是否直接重生。", "玩家", GameRuleValueType.BOOLEAN, "false"),
	GameRule("doInsomnia", "生成幻翼", "幻翼是否在夜晚生成。", "生成", GameRuleValueType.BOOLEAN, "true"),
	GameRule("doLimitedCrafting", "合成需要配方", "玩家只能使用已解锁的配方。", "玩家", GameRuleValueType.BOOLEAN, "false"),
	GameRule("doMobLoot", "生物战利品掉落", "生物死亡后是否掉落资源与经验。", "掉落", GameRuleValueType.BOOLEAN, "true"),
	GameRule("doMobSpawning", "生成生物", "生物是否自然生成(不影响刷怪笼/summon)。", "生成", GameRuleValueType.BOOLEAN, "true"),
	GameRule("doPatrolSpawning", "生成灾厄巡逻队", "控制灾厄巡逻队生成。", "生成", GameRuleValueType.BOOLEAN, "true"),
	GameRule("doTileDrops", "方块掉落", "破坏方块后是否掉落资源(含经验)。", "掉落", GameRuleValueType.BOOLEAN, "true"),
	GameRule("doTraderSpawning", "生成流浪商人", "控制流浪商人生成。", "生成", GameRuleValueType.BOOLEAN, "true"),
	GameRule("doVinesSpread", "藤蔓蔓延", "藤蔓能否随机向相邻方块蔓延。", "世界更新", GameRuleValueType.BOOLEAN, "true", "不影响洞穴藤蔓/缠怨藤/垂泪藤。"),
	GameRule("doWardenSpawning", "生成监守者", "监守者是否生成。", "生成", GameRuleValueType.BOOLEAN, "true"),
	GameRule("doWeatherCycle", "天气更替", "天气是否变化。", "世界更新", GameRuleValueType.BOOLEAN, "true"),
	GameRule("drowningDamage", "溺水伤害", "玩家是否承受窒息伤害。", "玩家", GameRuleValueType.BOOLEAN, "true"),
	GameRule("enderPearlsVanishOnDeath", "掷出的末影珍珠在死亡时消失", "玩家投掷的末影珍珠是否在其死亡时消失。", "玩家", GameRuleValueType.BOOLEAN, "true"),
	GameRule("fallDamage", "摔落伤害", "玩家是否承受摔落伤害。", "常用", GameRuleValueType.BOOLEAN, "true"),
	GameRule("fireDamage", "火焰伤害", "玩家是否承受火焰伤害。", "玩家", GameRuleValueType.BOOLEAN, "true"),
	GameRule("forgiveDeadPlayers", "宽恕死亡玩家", "被激怒的中立生物在目标玩家死亡后是否息怒。", "生物", GameRuleValueType.BOOLEAN, "true"),
	GameRule("freezeDamage", "冰冻伤害", "玩家是否承受冰冻伤害。", "玩家", GameRuleValueType.BOOLEAN, "true"),
	GameRule("globalSoundEvents", "全局声音事件", "特定事件声音可全图听见。", "杂项", GameRuleValueType.BOOLEAN, "true"),
	GameRule("keepInventory", "死亡后保留物品栏", "玩家死亡后是否保留物品与经验。", "常用", GameRuleValueType.BOOLEAN, "false"),
	GameRule("lavaSourceConversion", "允许流动熔岩转化为熔岩源", "流动熔岩在两面与源相邻时转化为源。", "世界更新", GameRuleValueType.BOOLEAN, "false"),
	GameRule("locatorBar", "启用玩家定位栏", "是否启用定位栏和路径点。", "玩家", GameRuleValueType.BOOLEAN, "true"),
	GameRule("logAdminCommands", "通告管理员命令", "是否在日志记录管理员使用的命令。", "聊天", GameRuleValueType.BOOLEAN, "true"),
	GameRule("maxCommandChainLength", "命令连锁执行数量限制", "连锁命令方块和函数的总数量限制。", "杂项", GameRuleValueType.INTEGER, "65536"),
	GameRule("maxCommandForkCount", "命令上下文数量限制", "execute等命令可用的上下文最大值。", "杂项", GameRuleValueType.INTEGER, "65536"),
	GameRule("maxEntityCramming", "实体挤压上限", "同位置可推动实体的上限，超过会挤压伤害。", "生物", GameRuleValueType.INTEGER, "24"),
	GameRule("minecartMaxSpeed", "矿车最大速度", "矿车默认最大速度(实验性矿车改进)。", "杂项", GameRuleValueType.INTEGER, "8", "单位格/秒，水下水平速度为一半。"),
	GameRule("mobExplosionDropDecay", "在生物爆炸中，一些方块不会掉落战利品", "生物爆炸会炸毁部分掉落物。", "掉落", GameRuleValueType.BOOLEAN, "true"),
	GameRule("mobGriefing", "允许破坏性生物行为", "生物是否能放置/修改/破坏方块或捡拾物品等。", "生物", GameRuleValueType.BOOLEAN, "true", "影响苦力怕、僵尸、末影人等；也影响村民繁殖与海龟蛋。"),
	GameRule("naturalRegeneration", "生命值自然恢复", "玩家在饥饿足够时是否自然回血。", "玩家", GameRuleValueType.BOOLEAN, "true"),
	GameRule("playersNetherPortalCreativeDelay", "创造模式下玩家在下界传送门中等待的时间", "创造模式穿越下界门所需刻数。", "玩家", GameRuleValueType.INTEGER, "0"),
	GameRule("playersNetherPortalDefaultDelay", "非创造模式下玩家在下界传送门中等待的时间", "非创造模式穿越下界门所需刻数。", "玩家", GameRuleValueType.INTEGER, "80"),
	GameRule("playersSleepingPercentage", "入睡占比", "跳过夜晚所需玩家占比。", "玩家", GameRuleValueType.INTEGER, "100", "0表示一人即可，>100则无法跳过。"),
	GameRule("projectilesCanBreakBlocks", "弹射物能否破坏方块", "控制弹射物能否破坏可被其破坏的方块。", "掉落", GameRuleValueType.BOOLEAN, "true", "影响紫颂花、滴水石锥、饰纹陶罐等。"),
	GameRule("pvp", "启用PvP", "玩家之间能否造成伤害。", "玩家", GameRuleValueType.BOOLEAN, "true"),
	GameRule("randomTickSpeed", "随机刻速率", "每区块每刻随机方块刻的频率。", "世界更新", GameRuleValueType.INTEGER, "3", "0禁用随机刻，较大值会加快生长/腐烂等。"),
	GameRule("reducedDebugInfo", "简化调试信息", "是否简化调试屏幕内容。", "杂项", GameRuleValueType.BOOLEAN, "false", "影响碰撞箱/区块边界显示等。"),
	GameRule("sendCommandFeedback", "发送命令反馈", "命令返回信息是否在聊天框显示。", "聊天", GameRuleValueType.BOOLEAN, "true", "也影响命令方块是否保存命令输出。"),
	GameRule("showDeathMessages", "显示死亡消息", "是否在聊天框显示玩家死亡消息。", "聊天", GameRuleValueType.BOOLEAN, "true", "也影响宠物死亡通知。"),
	GameRule("snowAccumulationHeight", "积雪厚度", "降雪时可堆积的最高雪层数。", "世界更新", GameRuleValueType.INTEGER, "1"),
	GameRule("spawnerBlocksEnabled", "启用刷怪笼方块", "是否允许刷怪笼与试炼刷怪笼运作。", "杂项", GameRuleValueType.BOOLEAN, "true"),
	GameRule("spawnMonsters", "生成怪物", "敌对生物是否能自然生成。", "生成", GameRuleValueType.BOOLEAN, "true"),
	GameRule("spawnRadius", "重生点半径", "首登或无重生点玩家在世界出生点周围的距离。", "玩家", GameRuleValueType.INTEGER, "10"),
	GameRule("spectatorsGenerateChunks", "允许旁观者生成地形", "旁观模式玩家是否能生成区块。", "玩家", GameRuleValueType.BOOLEAN, "true"),
	GameRule("tntExplodes", "允许TNT被点燃并爆炸", "TNT是否会爆炸。", "杂项", GameRuleValueType.BOOLEAN, "true"),
	GameRule("tntExplosionDropDecay", "在TNT爆炸中，一些方块不会掉落战利品", "TNT爆炸会炸毁部分掉落物。", "掉落", GameRuleValueType.BOOLEAN, "false"),
	GameRule("universalAnger", "无差别愤怒", "被激怒的中立生物是否攻击附近任何玩家。", "生物", GameRuleValueType.BOOLEAN, "false", "关闭forgiveDeadPlayers效果更佳。"),
	GameRule("waterSourceConversion", "允许流动水转化为水源", "流动水在两面与水源相邻时转化为水源。", "世界更新", GameRuleValueType.BOOLEAN, "true"),
)