package calebxzhou.rdi.model.pack

enum class ScriptType {
    ITEM_ADD,BLOCK_ADD,RECIPE_ADD,FUNCTION_ADD,LOOT_ADD,BIOME_ADD,ENTITY_ADD,ADVANCEMENT_ADD,TAG_ADD,
    ITEM_DEL,BLOCK_DEL,RECIPE_DEL,FUNCTION_DEL,LOOT_DEL,BIOME_DEL,ENTITY_DEL,ADVANCEMENT_DEL,TAG_DEL,
}